# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kostya <kostya@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/22 18:23:27 by kostya            #+#    #+#              #
#    Updated: 2022/01/22 19:22:08 by kostya           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	clang++ -Wall -Wextra -Werror -std=c++2a main.cpp -O2 -o test

clean:
	rm test

fclean: clean

re: fclean all
