# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kostya <kostya@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/06 17:10:59 by kostya            #+#    #+#              #
#    Updated: 2022/01/10 19:44:19 by kostya           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	clang++ -Wall -Wextra -Werror -O2 -o repl -std=c++2a main.cpp

clean:

fclean:
	rm repl

re: fclean all
